#!/bin/sh

rm -rf ~/.config/qtile
ln -sf $(pwd)/qtile ~/.config/qtile

rm -rf ~/.config/qutebrowser
ln -sf $(pwd)/qutebrowser ~/.config/qutebrowser

rm -rf ~/.config/alacritty
ln -sf $(pwd)/alacritty ~/.config/alacritty

rm -rf ~/.config/zathura
ln -sf $(pwd)/zathura ~/.config/zathura

rm -rf ~/.config/dunst
ln -sf $(pwd)/dunst ~/.config/dunst

rm -rf ~/.config/picom
ln -sf $(pwd)/picom ~/.config/picom

rm -rf ~/.config/rofi
ln -sf $(pwd)/rofi ~/.config/rofi

rm -rf ~/.pam_environment
ln -sf $(pwd)/pam_environment ~/.pam_environment

for s in $(ls $(pwd)/applications); do
	rm -rf ~/.local/share/applications$s
	ln -sf $(pwd)/applications/$s ~/.local/share/applications/$s
done
xdg-mime default zathura.desktop application/pdf
xdg-mime default pcmanfm.desktop inode/directory

for s in $(ls $(pwd)/scripts); do
	rm -rf ~/.local/bin/$s
	ln -sf $(pwd)/scripts/$s ~/.local/bin/$s
done
